{{- range $clusterConfigName, $configData := .Values.clusterConfig }}
{{- if $configData.enabled }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterConfig
metadata:
  name: {{ $clusterConfigName }}
  labels: {{- include "common.labels" $ | nindent 4 }}
  {{- with $configData.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $configData.promotionPolicies }}
  promotionPolicies:
    {{- toYaml $configData.promotionPolicies | nindent 4 }}
  {{- else }}
  {}
  {{- end }}
{{- end }}
{{ end }}