{{- range $projectName, $projectData := .Values.project }}
{{- if $projectData.enabled }}
{{- $resolvedProjectName := include "common.names.kargoProjectName" (list $ $projectName) }}
{{- range $rbacName, $rbacData := $projectData.rbac }}
{{- if $rbacData.create }}
---
{{- $templateRoot := deepCopy $ }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-kargo-%s" $resolvedProjectName $rbacName }}
  {{- with (merge ($rbacData.labels | default dict) (include "common.labels" $templateRoot | fromYaml)) }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- $localAnns := $rbacData.annotations | default dict }}
  {{- $kargoClaim := dict "rbac.kargo.akuity.io/claims" (toJson $rbacData.claims) }}
  {{- $mergedAnns := merge $localAnns $kargoClaim (include "common.annotations" $templateRoot | fromYaml) }}
  annotations:
    {{- toYaml $mergedAnns | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{ end }}
