version: 1.0.3
name: universal
description: a basic universal chart from my common library
keywords:
- common
- universal
sources:
- https://github.com/tylerhoadley/charts/tree/master/charts/universal
annotations:
  artifacthub.io/changes: |
    - "1.0.3"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.0.3
dependencies:
- name: common
  repository: https://github.com/tylerhoadley/charts/
  version: 1.0.3
maintainers:
- email: tyler.hoadley@computersthatwork.ca
  name: tylerhoadley
type: application

