image:
  # -- image repository
  repository: debian
  # -- image tag
  tag: latest
  # -- image pull policy
  # pullPolicy: Always

# -- environment variables.
# @default -- See below
# env:
#   # -- Set the container timezone
#   TZ: America/Toronto


# replicas: 1
service:
  main:
    # -- Enables or disables the service
    enabled: false