apiVersion: v2
appVersion: 1.0.4
dependencies:
- name: common
  repository: https://charts.computersthatwork.ca/
  version: 1.0.4
description: a basic universal chart from my common library
keywords:
- common
maintainers:
- email: tyler.hoadley@computersthatwork.ca
  name: tylerhoadley
sources:
- https://github.com/tylerhoadley/charts
kubeVersion: '>=1.16.0-0'
name: common
type: library
version: 1.0.4